### PR TITLE
refactor: name used in list-occurrences

### PR DESCRIPTION
**Pull request by ml019**
## Intent of Change
- Refactor (non-breaking change which improves the structure or operation of the implementation)

## Description
Switch to using the TypedName when listing and describing occurrences.

## Motivation and Context
It is unique and cleaner visually than the TypedRawName which is used currently.

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

### CODE REVIEW

**Comment by roleyfoley** [comment]
Is the typed name unique? The reason for adding the RawName was that he name was usually based on the Id of the component and that is only the Id of the component before any presence of a - 

So that meant you couldn't get unique occurrence names?

**Comment by ml019** [comment]
We were using RawName then switched to TypedRawName. It was adding the type on the key that was the key thing to get unique names, but the same effect will happen if we use TypedName and it is less verbose.

**Comment by roleyfoley** [comment]
But we added RawName pretty much for this command... 
Its required when you have multiple services using the same prefix ie. www-web, www-worker, www-task 

TypedName won't include the second part of the name which is required to get to each of the occurrences.

**Comment by ml019** [comment]
ok - well services is the one that breaks the rule then. 

I'll close this PR.

**Pull request closed without merging**
