### PR TITLE
refactor!: options context and generation parameters

### LINKED ISSUE #66: Move generation paramters to root command group
## Expected Behaviour
Generation parameters can be defined by a user and applied across all hamlet commands 

## Current Behaviour
Currently we have parameters at different command groups which represent the same configuration parameter. This makes it difficult to maintain and keep consistent. This currently an issue with the generation parameters  which are used anytime that we generate an output which is covered in just about all of the hamlet commands

```
@click.option(
    '-i',
    '--generation-input-source',
    help='source of input data to use when generating the template'
)
@click.option(
    '-p',
    '--generation-provider',
    help='provider for output generation',
    default=['aws'],
    multiple=True,
    show_default=True
)
@click.option(
    '-f',
    '--generation-framework',
    help='output framework to use for template generation',
    default='cf',
    show_default=True
)
```

## Possible Solution
move these options from the group level to the root hamlet level so that they are applied across all commands run in hamlet

## Context
Making things easier to use in the command line

### PR DESCRIPTION
**Pull request by roleyfoley**
## Description

This is a major refactor of the configuration context that we use to
define standard configuration applied to hamlet commands

- The generation framework, provider and input source are now top level commands and are part of the Options configuration class - Closes #66
- Environment variable parameters are now provided to each runner call rather than having env vars set at the start of the command. This shows where these parameters are being used and allows them to be accessed by the python executor
- Added log-level as a configuration option so that it can be added on the command line. It also respects the existing GENERATION_LOG_LEVEL setting and will prefer that
- cleans up parameter passing to remove touch points

## Motivation and Context
The main goal in this refactor is to build a set of common options which can be used by all hamlet commands and align with the global configuration options available from the bash executor 

## How Has This Been Tested?
Tested locally and using test suite 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions
- [x] This change will require updates to documentation which references the generation configuration options as they are no longer available on the group commands

## Checklist:
- [X] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [] None of the above.

### CODE REVIEW

**Comment by RossMurr4y** [comment]
@roleyfoley will need a rebase after recent merges

**Comment by roleyfoley** [comment]
> @roleyfoley will need a rebase after recent merges

@RossMurr4y rebase done

**Review by RossMurr4y — APPROVED** [review]

**Comment by RossMurr4y** [comment]
Looks like a new conflict has emerged @roleyfoley .

I'm happy to have merged after its resolved - It was only as I went to merge it myself that I found one of the other recent merges caused the new conflict

**Comment by roleyfoley** [comment]
@RossMurr4y Should be fixed up now and also added a couple of extra changes

**Review by RossMurr4y — APPROVED** [review]

**Pull request merged**
